nav:
  home: /
  about: /about/
  articles: /archives/
  projects: http://github.com/jackthorley

projects_url: http://github.com/jackthorley

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/coffee/coffee-plunger.svg
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/coffee/coffee-plunger-32-a.png
        gravatar: false
      android:
        url: /images/coffee/coffee-plunger-32-a.png
        gravator: false
      apple:
        url: /images/coffee/coffee-plunger-32-a.png
        gravator: false
    social_links:
        github: https://github.com/jackthorley
        #twitter: /
        #facebook: /
        #linkedin: /
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
