##############################################################################
# Content
##############################################################################

# Link to a page that gives an overview of all your projects.
# This can be an external link (e.g., to you GitHub profile) or to another
# page within your website.
projects_url: http://github.com/jackthorley


# Set the page direction to RTL or LTR. default is LTR. (if you set it 'rtl', the 'vazir' font will be loaded.)
direction: ltr
# Configure the navigation menu.
# A pair 'Key: url' will result in a link to 'url' with the name 'Key' in the
# navigation menu. Optionally, you can add translations for the 'Key' in
# languages/*.yml
nav:
  home: /
  about: /about/
  articles: /archives/
  projects: http://github.com/jackthorley

gravatar:
    email: 

logo:
    enabled: true
    width: 50
    height: 50
    url: /images/gold-svg.svg
    gravatar: false

favicon: 
  # eg. generate with http://realfavicongenerator.net/
  desktop:
    url: /images/gold-32.png
    gravatar: false
  android:
    url: /images/gold-32.png
    gravator: false
  apple:
    url: /images/gold-32.png
    gravator: false

social_links:
  github: https://github.com/jackthorley
  #twitter: /
  #facebook: /  
  linkedin: https://www.linkedin.com/in/jackthorley
  #mail: /

posts_overview:
  show_all_posts: true
  post_count: 5

highlight: rainbow

# Set the color scheme.
# Available color schemes are 'dark', 'light', 'classic' and 'white'.
# Alternatively, add your own custom color scheme to source/css/_colors.
colorscheme: dark

rss: false

# Turn your web pages into graph objects (see http://ogp.me).
open_graph: 
  fb_app_id:
  fb_admins:
  twitter_id:
  google_plus:


##############################################################################
# Plugins
##############################################################################

# Fill in your Disqus Comments Shortname to enable Disqus comments.
disqus: 
  enabled: false
  shortname: cactus-1

# Fill in your Google Analytics tracking ID to enable Google Analytics.
google_analytics: 
  enabled: false
  id: UA-86660611-1

# Fill in your Baidu Analytics tracking ID to enable Baidu Analytics.
baidu_analytics:
  enabled: false
  id: 2e6da3c375c8a87f5b664cea6d4cb29c

# Fill in you Gravatar user id / email if you want to use your gravatar as the
# logo and/or favicons of you website.